name: Compile-VSOMEIP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile_vsomeip:
    runs-on: windows-latest
    steps:
    - name: Windows - Install boost 1.78.0
      uses: MarkusJx/install-boost@v2.4.4
      id: Boost
      with:
          boost_version: 1.78.0
          platform: windows
          boost_install_dir: C:\runner
          toolset: msvc
          arch: x86
          cache: true

    - uses: actions/checkout@v3

    - name: Run CMake
      run: |
          cmake -Bbuild -D BOOST_ROOT=C:\runner\boost/boost\ .
          cmake --build build
